openapi: 3.0.3
info:
  title: Call Verification
  description: >-
    The Bandwidth Call Verification API can be used to retrieve fraud and
    spoofing risk scores for specific phone calls that are

    currently active on the Bandwidth network.
  contact:
    name: Bandwidth
    url: https://support.bandwidth.com
    email: support@bandwidth.com
  termsOfService: urn:tos
  version: 1.0.0
servers:
  - url: https://call-verification.bandwidth.com/api/v1
paths:
  /accounts/{accountId}/activeCalls/{activeCallId}:
    get:
      tags:
        - ActiveCalls
      summary: Retrieve the risk scores for a specific phone call
      description: >-
        Retrieve fraud and spoofing risk scores for a specific phone call that
        is currently active on the Bandwidth network.


        The fraud and spoofing scores returned by this API endpoint indicate how
        likely it is that the given phone call is 

        fraudulent or that the given phone call is coming from a spoofed phone
        number.


        Currently this API endpoint only supports inbound phone calls to phone
        numbers that have the call verifiaction feature

        enabled, but it may support other types of calls in the future.


        **Note**: This information is generated after a call is answered and is
        cached for only 30 minutes.  If you attempt

        to query this information before the score has been generated or after
        the 30 minute cache period expires, the API

        may return an HTTP 404.
      parameters:
        - $ref: '#/components/parameters/accountId'
        - $ref: '#/components/parameters/activeCallId'
      responses:
        '200':
          $ref: '#/components/responses/scoresResponse'
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '401':
          $ref: '#/components/responses/unauthorizedResponse'
        '403':
          $ref: '#/components/responses/forbiddenResponse'
        '404':
          $ref: '#/components/responses/notFoundResponse'
        '405':
          $ref: '#/components/responses/methodNotAllowedResponse'
        '429':
          $ref: '#/components/responses/tooManyRequestsResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
components:
  parameters:
    accountId:
      name: accountId
      schema:
        $ref: '#/components/schemas/AccountId'
      in: path
      required: true
    activeCallId:
      name: activeCallId
      schema:
        $ref: '#/components/schemas/ActiveCallId'
      in: path
      required: true
  responses:
    scoresResponse:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ActiveCallInfo'
    unauthorizedResponse:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
          examples:
            unauthorizedExample:
              $ref: '#/components/examples/unauthorizedErrorExample'
    badRequestResponse:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
          examples:
            badRequestExample:
              $ref: '#/components/examples/badRequestErrorExample'
    methodNotAllowedResponse:
      description: Method Not Allowed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
          examples:
            methodNotAllowedExample:
              $ref: '#/components/examples/methodNotAllowedErrorExample'
    forbiddenResponse:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
          examples:
            forbiddenExample:
              $ref: '#/components/examples/forbiddenErrorExample'
    notFoundResponse:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
          examples:
            notFoundExample:
              $ref: '#/components/examples/notFoundErrorExample'
    tooManyRequestsResponse:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
          examples:
            tooManyRequestsExample:
              $ref: '#/components/examples/tooManyRequestsErrorExample'
    internalServerErrorResponse:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
          examples:
            internalServerErrorExample:
              $ref: '#/components/examples/internalServerErrorErrorExample'
  schemas:
    AccountId:
      type: number
      description: >-
        The ID of the Bandwidth Dashboard account that the called number of the
        phone call is assigned to
      example: 9903248
    ActiveCallId:
      type: string
      description: >-
        The unique Bandwidth-generated identifier of a phone call provided by
        bandwith in the SIP invite for that call.

        Typically this value is provided in an X header in the SIP invite such
        as X-Customer-Ixn.
      example: MTU2MDI4ODE1XzgzMzQ4OTg4QDE5Mi4xNjguMTMyLjQx
    ActiveCallInfo:
      type: object
      description: >-
        All available information about a specific phone call that is currently
        active on the bandwidth network.
      properties:
        riskScore:
          $ref: '#/components/schemas/RiskScore'
    RiskScore:
      type: object
      description: The risk score for a specific phone call.
      properties:
        spoofingRisk:
          type: number
          description: >-
            A number between 0 and 100 that indicates the liklihood that the
            calling number on active phone call is 

            being spoofed (with 0 being the lowest possible risk and 100 being
            the highest possible risk).
          example: 9.83
        fraudRisk:
          type: number
          description: >-
            A number between 0 and 100 that indicates the level of risk that a
            phone call is spam or is otherwise coming

            from a fraudulent source.
          example: 72
    ApiError:
      type: object
      properties:
        error:
          type: string
          example: Internal Server Error
  examples:
    unauthorizedErrorExample:
      summary: Unauthorized
      value:
        error: Unauthorized
    badRequestErrorExample:
      summary: Bad Request
      value:
        error: Bad Request
    methodNotAllowedErrorExample:
      summary: Method Not Allowed
      value:
        error: Method Not Allowed
    forbiddenErrorExample:
      summary: Forbidden
      value:
        error: Forbidden
    notFoundErrorExample:
      summary: Not Found
      value:
        error: Fraud score not found
    tooManyRequestsErrorExample:
      summary: Too Many Requests
      value:
        error: Too Many Requests
    internalServerErrorErrorExample:
      summary: Internal Server Error
      value:
        error: Internal Server Error
  securitySchemes:
    Basic:
      type: http
      scheme: basic
      description: >-
        Basic authentication is a simple authentication scheme built into the
        HTTP protocol. To use it, send your HTTP requests with an Authorization
        header that contains the word Basic followed by a space and a
        base64-encoded string `username:password`.


        Example: `Authorization: Basic ZGVtbZpwQDU1dzByZA==`
security:
  - Basic: []
tags:
  - name: ActiveCalls
