openapi: 3.0.3
info:
  title: AI Bridge
  description: >-
    This AI Bridge API can be used to create and manage Providers and Bots for
    the Bandwidth AI Bridge product.
  contact:
    name: Bandwidth
    url: https://support.bandwidth.com/todo
    email: test@support.bandwidth.com
  termsOfService: https://www.bandwidth.com/legal/terms-of-use-bandwidthcom-web-sites/
  version: 1.0.0
servers:
  - url: TODO
    description: Production
paths:
  /accounts/{accountId}/aibridge/providers:
    get:
      summary: List All Providers
      operationId: listProviders
      description: Retrieve a list of all Providers for a single account.
      parameters:
        - $ref: '#/components/parameters/accountId'
      responses:
        '200':
          $ref: '#/components/responses/listProvidersResponse'
        '400':
          $ref: '#/components/responses/badRequestError'
        '401':
          $ref: '#/components/responses/unauthorizedError'
        '403':
          $ref: '#/components/responses/forbiddenError'
        '404':
          $ref: '#/components/responses/notFoundError'
        '405':
          $ref: '#/components/responses/notAllowedError'
        '429':
          $ref: '#/components/responses/tooManyRequestsError'
        5XX:
          $ref: '#/components/responses/internalServerError'
      tags:
        - Providers
    post:
      summary: Add a Provider
      operationId: createProvider
      description: Create a configuration for an new Provider.
      parameters:
        - $ref: '#/components/parameters/accountId'
      requestBody:
        $ref: '#/components/requestBodies/providerPostRequest'
      tags:
        - Providers
      responses:
        '200':
          $ref: '#/components/responses/createProviderResponse'
        '400':
          $ref: '#/components/responses/badRequestError'
        '401':
          $ref: '#/components/responses/unauthorizedError'
        '403':
          $ref: '#/components/responses/forbiddenError'
        '404':
          $ref: '#/components/responses/notFoundError'
        '405':
          $ref: '#/components/responses/notAllowedError'
        '429':
          $ref: '#/components/responses/tooManyRequestsError'
        5XX:
          $ref: '#/components/responses/internalServerError'
  /accounts/{accountId}/aibridge/providers/{providerId}:
    get:
      summary: Get a Provider by accountId and providerId
      operationId: getProvider
      description: >-
        Get a provider which corresponds to a particular account and provider
        Id.
      parameters:
        - $ref: '#/components/parameters/accountId'
        - $ref: '#/components/parameters/providerId'
      responses:
        '200':
          $ref: '#/components/responses/getProviderResponse'
        '400':
          $ref: '#/components/responses/badRequestError'
        '401':
          $ref: '#/components/responses/unauthorizedError'
        '403':
          $ref: '#/components/responses/forbiddenError'
        '404':
          $ref: '#/components/responses/notFoundError'
        '405':
          $ref: '#/components/responses/notAllowedError'
        '429':
          $ref: '#/components/responses/tooManyRequestsError'
        5XX:
          $ref: '#/components/responses/internalServerError'
      tags:
        - Providers
    put:
      summary: Replace a Provider
      operationId: replaceProvider
      description: Replace the configuration for an existing Provider.
      parameters:
        - $ref: '#/components/parameters/accountId'
        - $ref: '#/components/parameters/providerId'
      requestBody:
        $ref: '#/components/requestBodies/providerPutRequest'
      tags:
        - Providers
      responses:
        '200':
          $ref: '#/components/responses/getProviderResponse'
        '400':
          $ref: '#/components/responses/badRequestError'
        '401':
          $ref: '#/components/responses/unauthorizedError'
        '403':
          $ref: '#/components/responses/forbiddenError'
        '404':
          $ref: '#/components/responses/notFoundError'
        '405':
          $ref: '#/components/responses/notAllowedError'
        '429':
          $ref: '#/components/responses/tooManyRequestsError'
        5XX:
          $ref: '#/components/responses/internalServerError'
    patch:
      summary: Update a Provider
      operationId: updateProvider
      description: Update an existing Provider.
      parameters:
        - $ref: '#/components/parameters/accountId'
        - $ref: '#/components/parameters/providerId'
      requestBody:
        $ref: '#/components/requestBodies/providerPatchRequest'
      tags:
        - Providers
      responses:
        '200':
          $ref: '#/components/responses/getProviderResponse'
        '400':
          $ref: '#/components/responses/badRequestError'
        '401':
          $ref: '#/components/responses/unauthorizedError'
        '403':
          $ref: '#/components/responses/forbiddenError'
        '404':
          $ref: '#/components/responses/notFoundError'
        '405':
          $ref: '#/components/responses/notAllowedError'
        '429':
          $ref: '#/components/responses/tooManyRequestsError'
        5XX:
          $ref: '#/components/responses/internalServerError'
    delete:
      summary: Delete a Provider
      operationId: deleteProvider
      description: Delete an existing Provider
      parameters:
        - $ref: '#/components/parameters/accountId'
        - $ref: '#/components/parameters/providerId'
      responses:
        '204':
          $ref: '#/components/responses/deleteProviderResponse'
        '400':
          $ref: '#/components/responses/badRequestError'
        '401':
          $ref: '#/components/responses/unauthorizedError'
        '403':
          $ref: '#/components/responses/forbiddenError'
        '404':
          $ref: '#/components/responses/notFoundError'
        '405':
          $ref: '#/components/responses/notAllowedError'
        '429':
          $ref: '#/components/responses/tooManyRequestsError'
        5XX:
          $ref: '#/components/responses/internalServerError'
      tags:
        - Providers
components:
  parameters:
    accountId:
      name: accountId
      schema:
        $ref: '#/components/schemas/accountId'
      in: path
      required: true
    providerId:
      name: providerId
      in: path
      description: The related provider id.
      required: true
      schema:
        type: string
        example: 255d53ae-9cd8-4eed-8e33-0464c728e02a
    botId:
      name: botId
      in: path
      description: The related bot id.
      required: true
      schema:
        type: string
        example: 255d53ae-9cd8-4eed-8e33-0464c728e02a
  responses:
    listProvidersResponse:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/listProviderResponse'
          examples:
            listProviderResponseExample:
              $ref: '#/components/examples/listProviderResponseExample'
    getProviderResponse:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/providerResponse'
          examples:
            googleProviderExample:
              $ref: '#/components/examples/googleProviderGetResponseExample'
            awsProviderExample:
              $ref: '#/components/examples/awsProviderGetResponseExample'
            cognigyProviderExample:
              $ref: '#/components/examples/cognigyProviderGetResponseExample'
    createProviderResponse:
      description: A JSON object containing the details of the newly created Provider.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/postProviderResponseData'
          examples:
            googleProviderExample:
              $ref: '#/components/examples/googleProviderPostResponseExample'
            awsProviderExample:
              $ref: '#/components/examples/awsProviderPostResponseExample'
            cognigyProviderExample:
              $ref: '#/components/examples/cognigyProviderPostResponseExample'
    replaceProvidersResponse:
      description: A JSON object containing the updated details of the Provider.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/replaceProviderResponseData'
          examples:
            googleProviderExample:
              $ref: '#/components/examples/googleProviderPutResponseExample'
            awsProviderExample:
              $ref: '#/components/examples/awsProviderPostResponseExample'
            cognigyProviderExample:
              $ref: '#/components/examples/cognigyProviderPostResponseExample'
    updateProvidersResponse:
      description: A JSON object containing the updated details of the Provider.
      content:
        application/json:
          schema:
            oneOf:
              - $ref: '#/components/schemas/googleProviderResponseData'
              - $ref: '#/components/schemas/awsProviderResponseData'
              - $ref: '#/components/schemas/cognigyProviderResponseData'
          examples:
            googleProviderExample:
              $ref: '#/components/examples/googleProviderPatchResponseExample'
            awsProviderExample:
              $ref: '#/components/examples/awsProviderPatchResponseExample'
            cognigyProviderExample:
              $ref: '#/components/examples/cognigyProviderPatchResponseExample'
    deleteProviderResponse:
      description: The provider was successfully deleted. No response body is returned.
    badRequestError:
      description: A bad request error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/badRequestError'
          examples:
            badRequestErrorExample:
              $ref: '#/components/examples/badRequestErrorExample'
    notFoundError:
      description: A resource not found error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/notFoundError'
          examples:
            notFoundErrorExample:
              $ref: '#/components/examples/notFoundErrorExample'
    notAllowedError:
      description: Method Not Allowed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/methodNotAllowedError'
          examples:
            notAllowedErrorExample:
              $ref: '#/components/examples/notAllowedErrorExample'
    tooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/tooManyRequestsError'
          examples:
            tooManyRequestsErrorExample:
              $ref: '#/components/examples/tooManyRequestsErrorExample'
    internalServerError:
      description: An internal server error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/internalServerError'
          examples:
            internalServerErrorExample:
              $ref: '#/components/examples/internalServerErrorExample'
    unauthorizedError:
      description: Un unauthorized error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/authenticationError'
          examples:
            unauthorizedErrorExample:
              $ref: '#/components/examples/unauthorizedErrorExample'
    forbiddenError:
      description: Un unauthorized error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/authorizationError'
          examples:
            unauthorizedErrorExample:
              $ref: '#/components/examples/forbiddenErrorExample'
  schemas:
    providerResponse:
      title: Customer Response Payload
      type: object
      description: Response payload for customer information.
      properties:
        links:
          type: array
          items:
            $ref: '#/components/schemas/link'
          nullable: true
        data:
          oneOf:
            - $ref: '#/components/schemas/googleProviderResponseData'
            - $ref: '#/components/schemas/awsProviderResponseData'
            - $ref: '#/components/schemas/cognigyProviderResponseData'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/error'
          nullable: true
      required:
        - links
        - data
        - errors
    listProviderResponse:
      title: Customer Response Payload
      type: object
      description: Response payload for customer information.
      properties:
        links:
          type: array
          items:
            $ref: '#/components/schemas/link'
          nullable: true
        data:
          properties:
            totalCount:
              type: integer
              description: The total count of objects returned in the response.
            providers:
              type: array
              items:
                anyOf:
                  - $ref: '#/components/schemas/googleProviderResponseData'
                  - $ref: '#/components/schemas/awsProviderResponseData'
                  - $ref: '#/components/schemas/cognigyProviderResponseData'
          nullable: true
        errors:
          type: array
          items:
            $ref: '#/components/schemas/error'
          nullable: true
      required:
        - links
        - data
        - errors
    accountId:
      type: integer
      description: >-
        The ID of the Bandwidth Dashboard account that the called number of the
        phone call is assigned to.
      example: 1234567
    providersResponse:
      type: object
      description: All available information about a specific configured provider.
      properties:
        data:
          type: object
          properties:
            schema:
              $ref: '#/components/responses/getProviderResponse'
          nullable: true
    googleProviderResponseData:
      title: Google Provider Response Data
      type: object
      description: Contains Provider information.
      properties:
        name:
          $ref: '#/components/schemas/name'
        description:
          $ref: '#/components/schemas/description'
        type:
          $ref: '#/components/schemas/type'
        botUrl:
          $ref: '#/components/schemas/botUrl'
        googleProvider:
          $ref: '#/components/schemas/googleProviderResponse'
      nullable: true
      example:
        $ref: '#/components/examples/googleProviderExample'
    awsProviderResponseData:
      title: AWS Provider Response Data
      type: object
      properties:
        name:
          $ref: '#/components/schemas/name'
        description:
          $ref: '#/components/schemas/description'
        type:
          $ref: '#/components/schemas/type'
        botUrl:
          $ref: '#/components/schemas/botUrl'
        awsProvider:
          $ref: '#/components/schemas/awsProviderResponse'
      required:
        - type
        - fields
      nullable: true
      example:
        $ref: '#/components/examples/awsProviderExample'
    cognigyProviderResponseData:
      title: Cognigy Provider Response Data
      type: object
      properties:
        name:
          $ref: '#/components/schemas/name'
        description:
          $ref: '#/components/schemas/description'
        type:
          $ref: '#/components/schemas/type'
        botUrl:
          $ref: '#/components/schemas/botUrl'
        cognigyProvider:
          $ref: '#/components/schemas/cognigyProvider'
      required:
        - type
        - fields
      nullable: true
    example:
      $ref: '#/components/examples/cognigyProviderExample'
    googleProviderRequestData:
      title: Google Provider Request Data
      type: object
      description: Google provider request example.
      properties:
        name:
          $ref: '#/components/schemas/name'
        description:
          $ref: '#/components/schemas/description'
        type:
          $ref: '#/components/schemas/type'
        googleProvider:
          $ref: '#/components/schemas/googleProvider'
      example:
        $ref: '#/components/examples/googleProviderExample'
      required:
        - name
        - description
        - type
        - googleProvider
    awsProviderRequestData:
      title: AWS Provider Response Data
      type: object
      description: Aws request example.
      properties:
        name:
          $ref: '#/components/schemas/name'
        description:
          $ref: '#/components/schemas/description'
        type:
          $ref: '#/components/schemas/type'
        awsProvider:
          $ref: '#/components/schemas/awsProvider'
      required:
        - name
        - description
        - type
        - awsProvider
      example:
        $ref: '#/components/examples/awsProviderExample'
    cognigyProviderRequestData:
      title: Cognigy Provider Response Data
      type: object
      description: Cognigy request example
      properties:
        name:
          $ref: '#/components/schemas/name'
        description:
          $ref: '#/components/schemas/description'
        type:
          $ref: '#/components/schemas/type'
        cognigyProvider:
          $ref: '#/components/schemas/cognigyProvider'
      required:
        - name
        - description
        - type
        - cognigyProvider
    badRequestError:
      type: object
      properties:
        errorCode:
          type: integer
          description: The error code.
          example: 400
        errorMsg:
          type: string
          description: The error message.
          example: Malformed request data
      required:
        - errorCode
        - errorMsg
    authenticationError:
      type: object
      properties:
        errorCode:
          type: integer
          description: The error code.
          example: 401
        errorMsg:
          type: string
          description: The error message.
          example: Invalid credentials
      required:
        - errorCode
        - errorMsg
    authorizationError:
      type: object
      properties:
        errorCode:
          type: integer
          description: The error code.
          example: 403
        errorMsg:
          type: string
          description: The error message.
          example: Insufficient privileges
      required:
        - errorCode
        - errorMsg
    notFoundError:
      type: object
      properties:
        errorCode:
          type: integer
          description: The error code
          example: 404
        errorMsg:
          type: string
          description: The error message
          example: Resource not found
      required:
        - errorCode
        - errorMsg
    methodNotAllowedError:
      type: object
      properties:
        errorCode:
          type: integer
          description: The error code
          example: 405
        errorMsg:
          type: string
          description: The error message
          example: Method not allowed
      required:
        - errorCode
        - errorMsg
    tooManyRequestsError:
      type: object
      properties:
        errorCode:
          type: integer
          description: The error code
          example: 429
        errorMsg:
          type: string
          description: The error message
          example: Too many requests
      required:
        - errorCode
        - errorMsg
    internalServerError:
      type: object
      properties:
        errorCode:
          type: integer
          description: The error code.
          example: 500
        errorMsg:
          type: string
          description: The error message.
          example: Internal server error
      required:
        - errorCode
        - errorMsg
    createProvider:
      type: object
      properties:
        name:
          type: string
          example: Provider X2
          description: Description of Provider X.
        credentials:
          type: object
          properties:
            username:
              type: string
              example: johndoe
            password:
              type: string
              example: p@ssw0rd
          required:
            - username
            - password
      x-createProviderExample:
        name: Provider X2
        description: Description of Provider X2.
        credentials:
          username: johndoe
          password: p@ssw0rd
    replaceProvider:
      type: object
      properties:
        name:
          type: string
          example: Provider X
        description:
          type: string
          example: Description of Provider X.
        credentials:
          type: object
          properties:
            username:
              type: string
              example: johndoe
            password:
              type: string
              example: p@ssw0rd
          required:
            - username
            - credentials
      x-replaceProviderExample:
        name: Provider X (Updated)
        description: Description of Provider X (Updated)
        credentials:
          username: johndoe
          password: newp@ssword
    postProviderResponseData:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the new Provider.
          example: d1e921e4-a6ff-475b-8b20-d27b6f2bc6c9
        name:
          type: string
          description: Name of the new Provider.
          example: Provider X
        description:
          type: string
          description: Description of the new Provider.
          example: Configuration for Provider X
        type:
          type: string
          description: The type of provider, such as 'google', 'aws', or 'cognigy'.
          enum:
            - GOOGLE
            - AWS
            - COGNIGY
    replaceProviderResponseData:
      type: object
      properties:
        id:
          type: string
          description: The new unique identifier of the updated provider.
          example: f8a7a66a-4f4e-4b27-b557-7f3948a3cd2e
        name:
          type: string
          description: The new name of the updated provider.
          example: Provider Y
        description:
          type: string
          description: The new description of the updated provider.
          example: Configuration for Provider Y
        type:
          type: string
          description: The new type of the updated provider, such as 'google' or 'aws'.
          enum:
            - GOOGLE
            - AWS
            - COGNIGY
    updateProviderResponseData:
      type: object
      properties:
        id:
          type: string
          description: The unique identifier of the updated provider.
          example: f8a7a66a-4f4e-4b27-b557-7f3948a3cd2e
        name:
          type: string
          description: The new name of the updated provider.
          example: Provider Y
        description:
          type: string
          description: The new description of the updated provider.
          example: Configuration for Provider Y
        type:
          type: string
          description: The new type of the updated provider, such as 'google' or 'aws'.
          enum:
            - GOOGLE
            - AWS
            - COGNIGY
    updateProvider:
      type: object
      properties:
        name:
          type: string
          example: Provider X
        description:
          type: string
          example: Description of Provider X.
        type:
          type: string
          description: Type of provider.
          enum:
            - google
            - cognigy
            - aws
        credentials:
          oneOf:
            - $ref: '#/components/schemas/googleProviderCredentials'
            - $ref: '#/components/schemas/cognigyProviderCredentials'
            - $ref: '#/components/schemas/awsProviderCredentials'
        googleConfig:
          $ref: '#/components/schemas/googleProviderRequestData'
        cognigyConfig:
          $ref: '#/components/schemas/cognigyProviderRequestData'
        awsConfig:
          $ref: '#/components/schemas/awsProviderRequestData'
        cognigyResponse:
          type: object
          properties:
            type:
              type: string
            fields:
              type: object
              properties:
                ttsUrl:
                  type: string
                  description: A string representing the TTS URL.
                  example: http://example.com/tts
                sttUrl:
                  type: string
                  description: A string representing the STT URL.
                  example: http://example.com/stt
              required:
                - type
                - fields
    googleProviderCredentials:
      type: object
      properties:
        privateKey:
          type: string
          description: Private key for the Google account.
        clientEmail:
          type: string
          description: Email address for the Google account.
      required:
        - privateKey
        - clientEmail
      example:
        privateKey: abc123
        clientEmail: johndoe@example.com
    cognigyProviderCredentials:
      type: object
      properties:
        username:
          type: string
          description: Username for the Cognigy account.
        password:
          type: string
          description: Password for the Cognigy account.
      required:
        - username
        - password
      example:
        username: johndoe
        password: newp@ssword
    awsProviderCredentials:
      type: object
      properties:
        accessKey:
          type: string
          description: Access key for the AWS account.
        secretKey:
          type: string
          description: Secret key for the AWS account.
      required:
        - accessKey
        - secretKey
      example:
        accessKey: abc123
        secretKey: 456efg
    updateGoogleProvider:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/name'
        description:
          $ref: '#/components/schemas/description'
        type:
          $ref: '#/components/schemas/type'
        googleProvider:
          $ref: '#/components/schemas/googleProvider'
      required:
        - name
        - description
        - type
        - googleProvider
    updateAwsProvider:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/name'
        description:
          $ref: '#/components/schemas/description'
        type:
          $ref: '#/components/schemas/type'
        awsProvider:
          $ref: '#/components/schemas/awsProvider'
      required:
        - name
        - description
        - type
        - awsProvider
    updateCognigyProvider:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/name'
        description:
          $ref: '#/components/schemas/description'
        type:
          $ref: '#/components/schemas/type'
        cognigyProvider:
          $ref: '#/components/schemas/cognigyProvider'
      required:
        - name
        - description
        - type
        - cognigyProvider
    name:
      required:
        - name
      description: Name is a required field
    description:
      required:
        - description
      description: Description is a required field
    type:
      required:
        - type
      description: Type is a required field
    botUrl:
      type: string
      description: A string representing the bot endpoint.
      example: https://cognigy.ai/bots/mybot
    region:
      type: string
      description: A string representing the region.
      example: us-east-1
    location:
      type: string
      description: A string representing the location.
      example: Raleigh
    environment:
      type: string
      description: A string representing the environment.
      example: Production
    projectId:
      type: string
      description: A string representing the project ID.
      example: my-project
    agentId:
      type: string
      description: A string representing the agent ID.
      example: my-agent
      minLength: 1
    ttsUrl:
      type: string
      description: A string representing the TTS URL.
      example: http://example.com/tts
    sttUrl:
      type: string
      description: A string representing the STT URL.
      example: http://example.com/stt
    googleProvider:
      required:
        - googleProvider
        - region
        - location
        - environment
        - projectId
        - agentId
      description: Google Provider is required
      properties:
        region:
          $ref: '#/components/schemas/region'
        location:
          $ref: '#/components/schemas/location'
        environment:
          $ref: '#/components/schemas/environment'
        projectId:
          $ref: '#/components/schemas/projectId'
        agentId:
          $ref: '#/components/schemas/agentId'
        googleCredentials:
          $ref: '#/components/schemas/googleProviderCredentials'
    googleProviderResponse:
      required:
        - googleProvider
        - region
        - location
        - environment
        - projectId
        - agentId
      description: Google Provider is required
      properties:
        region:
          $ref: '#/components/schemas/region'
        location:
          $ref: '#/components/schemas/location'
        environment:
          $ref: '#/components/schemas/environment'
        projectId:
          $ref: '#/components/schemas/projectId'
        agentId:
          $ref: '#/components/schemas/agentId'
    googleCredentials:
      required:
        - googleCredentials
      description: Google Provider Credentials are required
      properties:
        googleCredentials:
          $ref: '#/components/schemas/googleProviderCredentials'
    awsProvider:
      required:
        - awsProvider
        - region
      description: Google Provider is required
      properties:
        region:
          $ref: '#/components/schemas/region'
    awsProviderResponse:
      required:
        - awsProvider
        - region
      description: Google Provider is required
      properties:
        region:
          $ref: '#/components/schemas/region'
        awsCredentials:
          $ref: '#/components/schemas/awsProviderCredentials'
    awsCredentials:
      required:
        - awsCredentials
      description: Google Provider Credentials are required
      properties:
        awsCredentials:
          $ref: '#/components/schemas/awsProviderCredentials'
    cognigyProvider:
      required:
        - cognigyProvider
      description: Cognigy Provider is required
      properties:
        ttsUrl:
          $ref: '#/components/schemas/ttsUrl'
        sttUrl:
          $ref: '#/components/schemas/sttUrl'
    cognigyCredentials:
      required:
        - googleCredentials
      description: Google Provider Credentials are required
      properties:
        cognigyCredentials:
          $ref: '#/components/schemas/cognigyProviderCredentials'
    error:
      title: Error
      type: object
      properties:
        id:
          type: string
          description: A unique identifier for this particular instance of this problem.
          example: optional-error-id
        type:
          type: string
          description: >-
            A short, human-readable summary of the problem that SHOULD NOT
            change from occurrence to occurrence of the problem.
          example: REQUEST_ERROR
        description:
          type: string
          description: >-
            A human-readable explanation that SHOULD be specific to this
            occurrence of the problem.
          example: There was an issue with a field in your request body
        code:
          type: integer
          format: int32
          description: >-
            An application-specific error code for services with extensive error
            scenarios to supplement `description`.
          minimum: 4
          example: 51130
        source:
          $ref: '#/components/schemas/errorSource'
        meta:
          $ref: '#/components/schemas/errorMeta'
      required:
        - description
    errorSource:
      title: Error Source
      type: object
      properties:
        parameter:
          type: string
          description: A string indicating which URI query parameter caused the error.
          example: someParameter
        field:
          type: string
          description: A string indicating which request body field caused the error.
          example: someField
        header:
          type: string
          description: A string indicating which header field caused the error.
          example: someHeader
        reference:
          type: string
          description: >-
            A string that references a resource ID or path to the resource (or
            non-existent resource) causing the error.
          example: /some/reference
    errorMeta:
      title: Error Meta
      type: object
      properties:
        message:
          type: string
          example: An optional metadata field
    link:
      title: Link
      type: object
      properties:
        href:
          type: string
          description: URI of the link.
          example: /relative/uri
        rel:
          type: string
          description: Specifies the relationship between this link and the resource.
          example: aRelatedResource
        method:
          type: string
          description: HTTP method to be used.
          example: GET
  requestBodies:
    providerPostRequest:
      content:
        application/json:
          schema:
            oneOf:
              - $ref: '#/components/schemas/googleProviderRequestData'
              - $ref: '#/components/schemas/awsProviderRequestData'
              - $ref: '#/components/schemas/cognigyProviderRequestData'
          examples:
            googleProviderExample:
              $ref: '#/components/examples/googleProviderExample'
            awsProviderExample:
              $ref: '#/components/examples/awsProviderExample'
            cognigyProviderExample:
              $ref: '#/components/examples/cognigyProviderExample'
    providerPutRequest:
      description: Updated configuration details for the Provider.
      required: true
      content:
        application/json:
          schema:
            oneOf:
              - $ref: '#/components/schemas/googleProviderRequestData'
              - $ref: '#/components/schemas/awsProviderRequestData'
              - $ref: '#/components/schemas/cognigyProviderRequestData'
          examples:
            googleProviderExample:
              $ref: '#/components/examples/googleProviderExample'
            awsProviderExample:
              $ref: '#/components/examples/awsProviderExample'
            cognigyProviderExample:
              $ref: '#/components/examples/cognigyProviderExample'
    providerPatchRequest:
      description: Updated configuration details for the Provider.
      required: true
      content:
        application/json:
          schema:
            oneOf:
              - $ref: '#/components/schemas/updateGoogleProvider'
              - $ref: '#/components/schemas/updateCognigyProvider'
              - $ref: '#/components/schemas/updateAwsProvider'
          examples:
            googleProvider:
              value:
                googleProvider:
                  name: My Google Provider
                  displayName: Updated Display Name
            awsProvider:
              value:
                awsProvider:
                  awsCredentials:
                    accessKeyId: myaccesskey
                    secretAccessKey: mysecretkey
            cognigyProvider:
              value:
                cognigyProvider:
                  name: My Cognigy Provider
                  ttsUrl: http://example.com/new-tts
  examples:
    providerExample:
      summary: A summary of a Provider
      value:
        schema:
          oneOf:
            - $ref: '#/components/examples/googleProviderExample'
            - $ref: '#/components/examples/awsProviderExample'
            - $ref: '#/components/examples/cognigyProviderExample'
    listProviderResponseExample:
      summary: An example of a Google provider
      value:
        links:
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: self
            method: GET
          - href: /providers
            rel: create
            method: POST
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: replace
            method: PUT
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: update
            method: PATCH
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: delete
            method: DELETE
        data:
          totalCount: 3
          providers:
            - id: b64b5e72-a850-4f38-98d4-5022cacd3f0f
              displayName: Google Provider
              type: GOOGLE
              botUrl: http://google-bot-url
              googleProvider:
                region: northamerica
                location: us-east-1
                environment: Production
                projectId: myproject
                agentId: myagent
            - id: b64b5e72-a850-4f38-98d4-5022cacd3f0r
              displayName: AWS Provider
              type: AWS
              awsProvider:
                botUrl: http://aws-bot-url
                Region: us-west-1
                awsCredentials:
                  accessKeyId: myaccesskey
                  secretAccessKey: mysecretkey
            - id: b64b5e72-a850-4f38-98d4-5022cacd3f0g
              displayName: Cognigy Provider
              type: COGNIGY
              cognigyProvider:
                botUrl: http://cognigy-bot-url
                TtsUrl: https://example.com/tts
                SttUrl: https://example.com/stt
        errors: null
    googleProviderExample:
      summary: An example of a Google provider
      value:
        displayName: Google Provider
        type: GOOGLE
        botUrl: http://google-bot-url
        googleProvider:
          region: northamerica
          location: us-east-1
          environment: Production
          projectId: myproject
          agentId: myagent
          googleCredentials:
            privateKey: samplekey
            clientEmai: email
    googleProviderGetResponseExample:
      summary: An example of a Google provider
      value:
        links:
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: self
            method: GET
          - href: /providers
            rel: create
            method: POST
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: replace
            method: PUT
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: update
            method: PATCH
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: delete
            method: DELETE
        data:
          id: b64b5e72-a850-4f38-98d4-5022cacd3f0f
          displayName: Google Provider
          type: GOOGLE
          botUrl: http://google-bot-url
          googleProvider:
            region: northamerica
            location: us-east-1
            environment: Production
            projectId: myproject
            agentId: myagent
        errors: null
    googleProviderPostResponseExample:
      summary: An example of a Google provider
      value:
        links:
          - href: /providers
            rel: self
            method: POST
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: customer
            method: GET
        data:
          id: b64b5e72-a850-4f38-98d4-5022cacd3f0f
          displayName: Google Provider
          type: GOOGLE
          botUrl: http://google-bot-url
          googleProvider:
            region: northamerica
            location: us-east-1
            environment: Production
            projectId: myproject
            agentId: myagent
        errors: null
    googleProviderPutResponseExample:
      summary: An example of a Google provider
      value:
        links:
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: self
            method: GET
          - href: /providers
            rel: create
            method: POST
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: replace
            method: PUT
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: update
            method: PATCH
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: delete
            method: DELETE
        data:
          id: b64b5e72-a850-4f38-98d4-5022cacd3f0f
          displayName: Google Provider
          type: GOOGLE
          botUrl: http://google-bot-url
          googleProvider:
            region: northamerica
            location: us-east-1
            environment: Production
            projectId: myproject
            agentId: myagent
        errors: null
    googleProviderPatchResponseExample:
      summary: An example of a Google provider
      value:
        links:
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: self
            method: GET
          - href: /providers
            rel: create
            method: POST
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: replace
            method: PUT
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: update
            method: PATCH
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: delete
            method: DELETE
        data:
          id: b64b5e72-a850-4f38-98d4-5022cacd3f0f
          displayName: Google Provider
          type: GOOGLE
          botUrl: http://google-bot-url
          googleProvider:
            region: northamerica
            location: us-east-1
            environment: Production
            projectId: myproject
            agentId: myagent
        errors: null
    awsProviderExample:
      summary: An example of an AWS provider
      value:
        name: AWS provider
        displayName: AWS Provider
        type: AWS
        awsProvider:
          botUrl: http://aws-bot-url
          Region: us-west-1
          awsCredentials:
            accessKeyId: myaccesskey
            secretAccessKey: mysecretkey
    awsProviderGetResponseExample:
      summary: An example of an AWS provider
      value:
        links:
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: self
            method: GET
          - href: /providers
            rel: create
            method: POST
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: replace
            method: PUT
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: update
            method: PATCH
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: delete
            method: DELETE
        data:
          name: AWS provider
          displayName: AWS Provider
          type: AWS
          awsProvider:
            botUrl: http://aws-bot-url
            Region: us-west-1
        errors: null
    awsProviderPostResponseExample:
      summary: An example of an AWS provider
      value:
        links:
          - href: /customers
            rel: self
            method: POST
          - href: /customers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: customer
            method: GET
        data:
          name: AWS provider
          displayName: AWS Provider
          type: AWS
          awsProvider:
            botUrl: http://aws-bot-url
            Region: us-west-1
        errors: null
    awsProviderPutResponseExample:
      summary: An example of an AWS provider
      value:
        links:
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: self
            method: GET
          - href: /providers
            rel: create
            method: POST
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: replace
            method: PUT
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: update
            method: PATCH
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: delete
            method: DELETE
        data:
          name: AWS provider
          displayName: AWS Provider
          type: AWS
          awsProvider:
            botUrl: http://aws-bot-url
            Region: us-west-1
        errors: null
    awsProviderPatchResponseExample:
      summary: An example of an AWS provider
      value:
        links:
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: self
            method: GET
          - href: /providers
            rel: create
            method: POST
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: replace
            method: PUT
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: update
            method: PATCH
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: delete
            method: DELETE
        data:
          name: AWS provider
          displayName: AWS Provider
          type: AWS
          awsProvider:
            botUrl: http://aws-bot-url
            Region: us-west-1
        errors: null
    cognigyProviderExample:
      summary: An example of a Cognigy provider
      value:
        name: Cognigy provider
        displayName: Cognigy Provider
        type: COGNIGY
        cognigyProvider:
          botUrl: http://cognigy-bot-url
          TtsUrl: https://example.com/tts
          SttUrl: https://example.com/stt
    cognigyProviderGetResponseExample:
      summary: An example of a Cognigy provider
      value:
        links:
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: self
            method: GET
          - href: /providers
            rel: create
            method: POST
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: replace
            method: PUT
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: update
            method: PATCH
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: delete
            method: DELETE
        data:
          name: Cognigy provider
          displayName: Cognigy Provider
          type: COGNIGY
          cognigyProvider:
            botUrl: http://cognigy-bot-url
            TtsUrl: https://example.com/tts
            SttUrl: https://example.com/stt
        errors: null
    cognigyProviderPostResponseExample:
      summary: An example of a Cognigy provider
      value:
        links:
          - href: /customers
            rel: self
            method: POST
          - href: /customers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: customer
            method: GET
        data:
          name: Cognigy provider
          displayName: Cognigy Provider
          type: COGNIGY
          cognigyProvider:
            botUrl: http://cognigy-bot-url
            TtsUrl: https://example.com/tts
            SttUrl: https://example.com/stt
        errors: null
    cognigyProviderPutResponseExample:
      summary: An example of a Cognigy provider
      value:
        links:
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: self
            method: GET
          - href: /providers
            rel: create
            method: POST
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: replace
            method: PUT
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: update
            method: PATCH
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: delete
            method: DELETE
        data:
          name: Cognigy provider
          displayName: Cognigy Provider
          type: COGNIGY
          cognigyProvider:
            botUrl: http://cognigy-bot-url
            TtsUrl: https://example.com/tts
            SttUrl: https://example.com/stt
        errors: null
    cognigyProviderPatchResponseExample:
      summary: An example of a Cognigy provider
      value:
        links:
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: self
            method: GET
          - href: /providers
            rel: create
            method: POST
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: replace
            method: PUT
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: update
            method: PATCH
          - href: /providers/b64b5e72-a850-4f38-98d4-5022cacd3f0f
            rel: delete
            method: DELETE
        data:
          name: Cognigy provider
          displayName: Cognigy Provider
          type: COGNIGY
          cognigyProvider:
            botUrl: http://cognigy-bot-url
            TtsUrl: https://example.com/tts
            SttUrl: https://example.com/stt
        errors: null
    badRequestErrorExample:
      summary: An example of a generic Bad Request Error.
      value:
        links: null
        data: null
        errors:
          - id: optional-error-id
            type: bad-request
            description: There was an issue with your request.
            code: 205617
    unauthorizedErrorExample:
      summary: An example of a generic Unauthorized Error
      value:
        links: null
        data: null
        errors:
          - id: optional-error-id
            type: authentication-credentials
            description: Invalid or missing credentials.
            code: 206401
    forbiddenErrorExample:
      summary: An example of a generic Unauthorized Error.
      value:
        links: null
        data: null
        errors:
          - id: optional-error-id
            type: resource-permissions
            description: User does not have permissions to access this resource.
            code: 109107
    notFoundErrorExample:
      summary: An example of a generic Not Found Error.
      value:
        links: null
        data: null
        errors:
          - id: optional-error-id
            type: resource-not-found
            description: The resource specified cannot be found.
            code: 50420
    notAllowedErrorExample:
      summary: An example of a Method Not Allowed error.
      value:
        links: null
        data: null
        errors:
          - id: optional-error-id
            type: method-not-allowed
            description: >-
              The HTTP request method is not supported for the requested
              resource.
            code: 405
    tooManyRequestsErrorExample:
      summary: An example of a Too Many Requests error.
      value:
        links: null
        data: null
        errors:
          - id: optional-error-id
            type: too-many-requests
            description: >-
              The user has sent too many requests in a given amount of time
              (rate limiting).
            code: 429
    internalServerErrorExample:
      summary: An example of a generic Internal Server Error.
      value:
        links: null
        data: null
        errors:
          - id: optional-error-id
            type: internal-server-error
            description: >-
              Unexpected internal server error. Contact Bandwidth Customer
              Support if this problem persists.
            code: 32030
