{
    "swagger": "2.0",
    "info": {
        "version": "",
        "title": "CatapultApplications",
        "description": "This API provides access to the Applications resource, that enables the invoking party to create and configure applications, where an application in this case is defined by an ID and a callback URL."
    },
    "host": "applications.stage.catapult.inetwork.com",
    "schemes": [
        "https"
    ],
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "paths": {
        "/applications": {
            "post": {
                "operationId": "POST_applications",
                "summary": "Create Application",
                "tags": [
                    "Applications"
                ],
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/application"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "An instance of the created Application resource, containing the ID of the Application.",
                        "schema": {
                            "$ref": "#/definitions/application"
                        },
                        "examples": {
                            "application/json": {
                                "id": "a-abcd123uniqueid",
                                "userId": "u-hw24bzfvnobnnozf8qrpcnq",
                                "name": "Test Application",
                                "url": "https://requestb.in/18rdfkc1",
                                "credentials": {
                                    "username": "bandwidthuser123",
                                    "password": "correctbatteryhorsestaple"
                                }
                            }
                        }
                    }
                },
                "description": "Create an application"
            },
            "get": {
                "operationId": "GET_applications",
                "summary": "List Applications",
                "tags": [
                    "Applications"
                ],
                "parameters": [
                    {
                        "name": "accountId",
                        "in": "query",
                        "type": "string",
                        "required": true,
                        "description": "The accountId is the catapult-associated account that is being used to host all of the Applications.  This account can either be a 'normal' Catapult user id of the form u-lasdjflroejfdfosa or an IRIS account ID pre-associated with an IRIS account."
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The anticipated response contains a list of Applications associated with the account indicated in the queryparameter",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/application"
                            }
                        },
                        "examples": {
                            "application/json": [
                                {
                                    "id": "a-abcd123uniqueid",
                                    "userId": "u-hw24bzfvnobnnozf8qrpcnq",
                                    "name": "Test Application 1",
                                    "url": "https://requestb.in/18rdfkc1",
                                    "credentials": {
                                        "username": "bandwidthuser123",
                                        "password": "correctbatteryhorsestaple"
                                    }
                                },
                                {
                                    "id": "a-xyz456uniqueid",
                                    "userId": "u-hw24bzfvnobnnozf8qrpcnq",
                                    "name": "Test Application 2",
                                    "url": "https://requestb.in/18rdffd1",
                                    "credentials": {
                                        "username": "bandwidthuser123",
                                        "password": "correctbatteryhorsestaple"
                                    }
                                }
                            ]
                        }
                    }
                },
                "description": "Retrieve a list of applications from the applications service"
            }
        },
        "/applications/{applicationId}": {
            "parameters": [
                {
                    "name": "applicationId",
                    "in": "path",
                    "required": true,
                    "type": "string"
                }
            ],
            "delete": {
                "operationId": "DELETE_applications-applicationId",
                "summary": "Delete Application",
                "tags": [
                    "Applications"
                ],
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "404": {
                        "description": "",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "response": {
                                    "type": "string"
                                }
                            }
                        },
                        "examples": {
                            "application/json": {
                                "response": "Application [5d48dd7a-9d85-4ff7-9ce1-b895510848f2] not found"
                            }
                        }
                    }
                },
                "description": "delete an Application."
            },
            "get": {
                "operationId": "GET_applications-applicationId",
                "summary": "Get Application",
                "tags": [
                    "Applications"
                ],
                "responses": {
                    "200": {
                        "description": "The response is the identified Application - reflecting all of the provisioned fields",
                        "schema": {
                            "$ref": "#/definitions/application"
                        },
                        "examples": {
                            "application/json": {
                                "id": "a-abcd123uniqueid",
                                "userId": "u-hw24bzfvnobnnozf8qrpcnq",
                                "name": "Test Application",
                                "url": "https://requestb.in/18rdfkc1",
                                "credentials": {
                                    "username": "bandwidthuser123",
                                    "password": "correctbatteryhorsestaple"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Failure to find identified resource",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "response": {
                                    "type": "string"
                                }
                            }
                        },
                        "examples": {
                            "application/json": {
                                "response": "Application [5d48dd7a-9d85-4ff7-9ce1-b895510848f2] not found"
                            }
                        }
                    }
                },
                "description": "Retrieve an identified Application "
            },
            "put": {
                "summary": "Update an entire application",
                "tags": [
                    "Applications"
                ],
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/application"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "An instance of the updated Application resource, containing the ID of the Application.",
                        "schema": {
                            "$ref": "#/definitions/application"
                        },
                        "examples": {
                            "application/json": {
                                "id": "a-abcd123uniqueid",
                                "userId": "u-hw24bzfvnobnnozf8qrpcnq",
                                "name": "Test Application",
                                "url": "https://requestb.in/18rdfkc1",
                                "credentials": {
                                    "username": "bandwidthuser123",
                                    "password": "correctbatteryhorsestaple"
                                }
                            }
                        }
                    }
                }
            },
            "patch": {
                "summary": "Selectively update an application",
                "tags": [
                    "Applications"
                ],
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/application"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "An instance of the updated Application resource, containing the ID of the Application.",
                        "schema": {
                            "$ref": "#/definitions/application"
                        },
                        "examples": {
                            "application/json": {
                                "id": "a-abcd123uniqueid",
                                "userId": "u-hw24bzfvnobnnozf8qrpcnq",
                                "name": "Test Application",
                                "url": "https://requestb.in/18rdfkc1",
                                "credentials": {
                                    "username": "bandwidthuser123",
                                    "password": "correctbatteryhorsestaple"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/applications/{applicationId}/metadata" : {
          "get" : {
            "operationId" : "getAllMetadataForApplication",
            "parameters" : [ {
              "name" : "applicationId",
              "in" : "path",
              "required" : true,
              "type" : "string"
            } ],
            "responses" : {
              "200" : {
                "description" : "successful operation",
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/definitions/Metadata"
                  }
                }
              }
            }
          },
          "post" : {
            "operationId" : "createMetadata",
            "parameters" : [ {
            "in" : "body",
            "name" : "body",
            "required" : false,
            "schema" : {
              "$ref" : "#/definitions/Metadata"
            }
          }, {
              "name" : "applicationId",
              "in" : "path",
              "required" : true,
              "type" : "string"
            } ],
            "responses" : {
              "200" : {
                "description" : "successful operation",
                "schema" : {
                  "$ref" : "#/definitions/Metadata"
              }
            }
          }
        },
          "put" : {
            "operationId" : "updateMetadata",
            "parameters" : [ {
              "in" : "body",
              "name" : "body",
              "required" : false,
              "schema" : {
                "$ref" : "#/definitions/Metadata"
              }
            }, {
            "name" : "applicationId",
            "in" : "path",
            "required" : true,
            "type" : "string"
            } ],
            "responses" : {
              "200" : {
                "description" : "successful operation",
                "schema" : {
                  "$ref" : "#/definitions/Metadata"
                }
              }
            }
          }
        },
        "/applications/{applicationId}/metadata/{key}" : {
          "get" : {
            "operationId" : "getMetadata",
            "parameters" : [ {
              "name" : "applicationId",
              "in" : "path",
              "required" : true,
              "type" : "string"
          }, {
            "name" : "key",
            "in" : "path",
            "required" : true,
            "type" : "string"
          } ],
          "responses" : {
            "200" : {
              "description" : "successful operation",
              "schema" : {
                "$ref" : "#/definitions/Metadata"
              }
            }
          }
        },
          "delete" : {
            "operationId" : "deleteMetadata",
            "parameters" : [ {
              "name" : "applicationId",
              "in" : "path",
              "required" : true,
              "type" : "string"
          }, {
            "name" : "key",
            "in" : "path",
            "required" : true,
            "type" : "string"
          } ],
          "responses" : {
            "default" : {
              "description" : "successful operation"
            }
          }
        }
      }
    },
    "definitions": {
        "application": {
            "title": "Application",
            "type": "object",
            "example": {
                "accountId": "u-hw24bzfvnobnnozf8qrpcnq",
                "name": "Test Application",
                "url": "https://requestb.in/18rdfkc1",
                "credentials": {
                    "username": "bandwidthuser123",
                    "password": "correctbatteryhorsestaple"
                }
            },
            "properties": {
                "id": {
                    "type": "string",
                    "description": "The ID is the Identifier issued by the Application Service to uniquely identify the Application.  It will be ignored in a POST."
                },
                "accountId": {
                    "type": "string",
                    "description": "The unique ID of the owner of this Application. This should match the userId of API Tokens to be used by this Application.",
                    "minLength": 1
                },
                "name": {
                    "type": "string",
                    "description": "A name that the end user can set (or update) to help them identify the Application"
                },
                "url": {
                    "type": "string",
                    "description": "The URL that Catapult should make HTTP requests to for callbacks. This should be HTTPS if credentials are set.",
                    "minLength": 1,
                    "format": "uri"
                },
                "credentials": {
                    "$ref": "#/definitions/credentials"
                }
            },
            "required": [
                "accountId",
                "name",
                "url"
            ],
            "description": "The Application is the core resource - reflecting the callback url and all required decoration required to manage the Application, as well as to allow it to be used by the customer's server."
        },
        "credentials": {
            "title": "Credentials",
            "type": "object",
            "properties": {
                "username": {
                    "type": "string",
                    "minLength": 1,
                    "description": "Basic auth username used for HTTP callbacks"
                },
                "password": {
                    "type": "string",
                    "description": "Basic auth password used for HTTP callbacks",
                    "minLength": 1
                }
            },
            "required": [
                "username",
                "password"
            ],
            "example": {
                "username": "bandwidth_user_123",
                "password": "correctbatteryhorsestaple"
            }
        },
        "application-list": {
            "title": "Application List",
            "type": "array",
            "items": {
                "$ref": "#/definitions/application"
            }
        },
        "Metadata" : {
          "title": "Metadata",
          "type" : "object",
          "properties" : {
            "key" : {
              "type" : "string",
              "minLength": 1
            },
            "value" : {
              "type" : "string"
            }
          }
        }
    }
}
